### ISSUE TITLE
Java EE 8 BOM?

### ISSUE THREAD

**Issue by JensPiegsa** [wildfly/boms#39]
Is there already a bom file containing the dependency version for ee8.preview.mode?

**Comment by JWGmeligMeyling** [comment]
Appears that there isn't. Perhaps with WF14's full EE8 compatibility?

**Comment by emmartins** [comment]
hello, we are going to remove this issue feature since it's not supposed to be monitored and taken care, please use instead the mail lists and/or JIRAs to request fixes and features. Regarding java ee BOMS these are coming shortly.

Regards and sorry for any inconvenience closing this github functionality may represent.

--E
